version: 0.0
os: linux
permissions:
  - object: /srv/www/avatar-creator-react
    pattern: "**/*"
    owner: www-data
    group: www-data
    mode: 664
    type:
      - file
  - object: /srv/www/avatar-creator-react
    pattern: "**/*"
    owner: www-data
    group: www-data
    mode: 775
    type:
      - directory
hooks:
  AfterInstall:
    - location: deployment/configure
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment/restart_server
      timeout: 300
      runas: root